// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockTradingApp.Data;

#nullable disable

namespace StockTradingApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231028212353_InitialAdd")]
    partial class InitialAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockTradingApp.Data.Trade", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TradeId"));

                    b.Property<double?>("BuyPrice")
                        .HasColumnType("float");

                    b.Property<double?>("DollarStopLoss")
                        .HasColumnType("float");

                    b.Property<int?>("NumberSharesBought")
                        .HasColumnType("int");

                    b.Property<int?>("NumberSharesSold")
                        .HasColumnType("int");

                    b.Property<double?>("SellPrice")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ShareBuyDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ShareSellDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TradeId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("StockTradingApp.Data.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("EntryPrice")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumberSharesEntered")
                        .HasColumnType("int");

                    b.Property<int?>("NumberSharesExited")
                        .HasColumnType("int");

                    b.Property<double?>("SellPrice")
                        .HasColumnType("float");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("TradeId");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("StockTradingApp.Data.Transaction", b =>
                {
                    b.HasOne("StockTradingApp.Data.Trade", "Trade")
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });
#pragma warning restore 612, 618
        }
    }
}
